services:
  nginx:
    image: nginx:1.28.0
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./.docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
    depends_on:
      php-fpm:
        condition: service_started
    networks:
      - laravel-dev

  php-fpm:
    build:
      context: .
      dockerfile: ./.docker/common/php-fpm/Dockerfile
      target: dev
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    container_name: php-fpm
    env_file:
      - .env
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www
      - ./.docker/dev/php-fpm/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - postgres
      - redis
      - mailpit
      - minio
    networks:
      - laravel-dev

  workspace:
    build:
      context: .
      dockerfile: ./.docker/dev/workspace/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    container_name: workspace
    ports:
      - "${VITE_PORT:-5173}:5173"
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - ./:/var/www
      - ./.docker/dev/php-fpm/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - postgres
      - redis
      - mailpit
      - minio
    networks:
      - laravel-dev

  postgres:
    image: postgres:17.6
    container_name: postgres
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - laravel-dev

  redis:
    image: redis:8.2.2-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - laravel-dev

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - '${MAILPIT_PORT:-1025}:1025'
      - '${MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - laravel-dev

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    restart: unless-stopped
    ports:
      - "${MINIO_PORT:-9001}:9001"
      - "${MINIO_CONSOLE_PORT:-8900}:8900"
    volumes:
      - minio-storage:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    command: server /data --console-address ":8900" --address ":9001"
    networks:
      - laravel-dev

networks:
  laravel-dev:

volumes:
  postgres-data:
  redis-data:
  minio-storage:
