services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/prod/nginx/Dockerfile
    container_name: nginx
    restart: unless-stopped
    volumes:
      - laravel-storage:/var/www/storage:ro
      - laravel-public-assets:/var/www/public/build:ro
    ports:
      - "${NGINX_PORT:-80}:80"
    environment:
      - NGINX_HOST=localhost
    depends_on:
      - php-fpm
    networks:
      - laravel-prod

  php-fpm:
    build:
      context: .
      dockerfile: ./.docker/common/php-fpm/Dockerfile
      target: prod
    container_name: php-fpm
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - laravel-public-assets:/var/www/public/build
      - laravel-storage:/var/www/storage
    depends_on:
      - postgres
      - redis
      - mailpit
      - minio
    networks:
      - laravel-prod
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:17.6
    container_name: postgres
    restart: unless-stopped
    user: postgres
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - laravel-prod
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.2.2-alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - laravel-prod
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    restart: unless-stopped
    ports:
      - "${MINIO_PORT:-9001}:9001"
      - "${MINIO_CONSOLE_PORT:-8900}:8900"
    volumes:
      - minio-storage:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    command: server /data --console-address ":8900" --address ":9001"
    networks:
      - laravel-prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8900/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  laravel-prod:

volumes:
  postgres-data:
  laravel-storage:
  laravel-public-assets:
  minio-storage:
